### ISSUE TITLE
Incorrect method used

### ISSUE THREAD

**Issue by Rodney-Lewis** [FRC-1250/Team-1250-PowerUp-Code#2]
https://github.com/FRC-1250/Team-1250-PowerUp-Code/blob/3ee963df903e449465cc7e96a948753a82556c92/src/org/usfirst/frc/team1250/robot/commands/Cmd_EleHome.java#L23

This method returns you to -1 in TICKS which in our case, is slightly above the ground (~0.0009 in).

Would resolve this by making it similar to scale.
`Robot.s_elevator.setLiftPosition(Robot.s_elevator.SCALE_POS);`

I propose we avoid using function overloading all together because it's fairly easy to miss. (Damien - Function overloading allows for multiple functions to be named the same in the same scope but accept different parameters. The code knows which one to select based on what you pass into it)

**Comment by ruiqim** [comment]
Nice catch, I'm on the fence about whether we should or should not use method overloading.... I would prefer we stick to DRY coding as much as possible. Let me know how we can better do this...

**Comment by RincewindBoi** [comment]
Resolved in commit 0b5eed6fd923b790dc78e3763ce12b70b15f9ac1.
